DROP TABLE IF EXISTS CONTACTS;
CREATE TABLE CONTACTS
(
    ID   BIGSERIAL PRIMARY KEY,
    EMAIL  VARCHAR(255),
    PHONE_NUMBER  VARCHAR(255)
);

DROP TABLE IF EXISTS STATUSES;
CREATE TABLE STATUSES
(
    ID   BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255)
);

DROP TABLE IF EXISTS EMPLOYEES;
CREATE TABLE EMPLOYEES
(
    ID   BIGSERIAL PRIMARY KEY,
    FULL_NAME VARCHAR(255),
    CONTACT_ID BIGINT REFERENCES CONTACTS (ID) ON DELETE CASCADE,
    STATUS_ID BIGINT REFERENCES STATUSES (ID) ON DELETE CASCADE,
    BIRTH_DATE TIMESTAMP
);

DROP TABLE IF EXISTS EQUIPMENTS;
CREATE TABLE EQUIPMENTS
(
    ID   BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255),
    EMPLOYEE_ID BIGINT REFERENCES EMPLOYEES (ID) ON DELETE CASCADE
);



