DROP TABLE IF EXISTS CONTACTS;
CREATE TABLE CONTACTS
(
    ID   BIGSERIAL PRIMARY KEY,
    EMAIL  VARCHAR(255),
    PHONE_NUMBER  VARCHAR(255)
);

DROP TABLE IF EXISTS EMPLOYEES;
CREATE TABLE EMPLOYEES
(
    ID   BIGSERIAL PRIMARY KEY,
    FULL_NAME VARCHAR(255),
    CONTACT_ID BIGINT REFERENCES CONTACTS (ID) ON DELETE CASCADE,
    BIRTH_DATE TIMESTAMP
);

