spring:
  datasource:
    url: "jdbc:h2:mem:maindb"
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
      enabled: true

  sql:
    init:
      mode: always
      schema-locations: "classpath:schema.sql"