DROP TABLE IF EXISTS CONTACTS;
DROP TABLE IF EXISTS EMPLOYEE_HISTORIES;
DROP TABLE IF EXISTS EMPLOYEES;

CREATE TABLE EMPLOYEES
(
    ID   BIGSERIAL PRIMARY KEY,
    FULL_NAME VARCHAR(255) NOT NULL,
    BIRTH_DATE TIMESTAMP
);
CREATE TABLE CONTACTS
(
    ID   BIGSERIAL PRIMARY KEY,
    EMAIL  VARCHAR(255) NOT NULL,
    PHONE_NUMBER  VARCHAR(255) NOT NULL,
    EMPLOYEE_ID BIGINT REFERENCES EMPLOYEES (ID) ON DELETE CASCADE
);
CREATE TABLE EMPLOYEE_HISTORIES
(
    ID   BIGSERIAL PRIMARY KEY,
    DAY_COST NUMERIC(20, 2) NOT NULL,
    BEGIN_DATE DATE NOT NULL,
    EMPLOYEE_ID BIGINT REFERENCES EMPLOYEES (ID) ON DELETE CASCADE
);