create table if not exists users
(
    id       integer generated by default as identity,
    username varchar_ignorecase(50)  not null unique,
    password varchar_ignorecase(500) not null,
    enabled  boolean                 not null
);

create table if not exists authorities
(
    username  varchar_ignorecase(50) not null,
    authority varchar_ignorecase(50) not null,
    constraint fk_authorities_users foreign key (username) references users (username)
);

create unique index ix_auth_username on authorities (username, authority);