DROP TABLE IF EXISTS EMPLOYEES;
CREATE TABLE EMPLOYEES
(
    ID           BIGSERIAL PRIMARY KEY,
    FULL_NAME    VARCHAR(255) NOT NULL,
    EMAIL        VARCHAR(255),
    PHONE_NUMBER VARCHAR(255) NOT NULL,
    BIRTH_DATE   TIMESTAMP    NOT NULL
);