spring:
  r2dbc:
    url: "r2dbc:h2:file:///./testdb"
    username: sa
    password:
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
      enabled: true

  sql:
    init:
      mode: always
      schema-locations: "classpath:schema.sql"

