
DROP TABLE IF EXISTS EMPLOYEES;
CREATE TABLE EMPLOYEES
(
    ID           BIGSERIAL PRIMARY KEY,
    FULL_NAME    VARCHAR(255),
    BIRTH_DATE   TIMESTAMP,
    EMAIL        VARCHAR(255),
    PHONE_NUMBER VARCHAR(255)
);

